### ISSUE TITLE
Add shooting and reload

### ISSUE THREAD

**Issue by Karinexmachina** [first-assault-reborn/FirstAssaultReborn#48]
The addition of shooting and reload code and animation hooks for the character controller

**Comment by Karinexmachina** [comment]
![image](https://user-images.githubusercontent.com/45721251/56827560-15481600-6857-11e9-83e2-8cbcbb0abda0.png)

Weapon does reload tac fine but it needs to be disabled if ammo is full.

Empty reload causes all the animations to stop working until the ammo is 0 or below again reloading the issue will still persist.

There might be a bug with crouching as well. Animations don't seem to transition when moving and going into crouch.

Not sure if its an error on my end but reload while crouching is a bit funny.. when i restarted the playercharacter they werent able to reload while crouched for some reason..

![image](https://user-images.githubusercontent.com/45721251/56829062-a8367f80-685a-11e9-9241-85bc4f335d57.png)

For future reference:
Running needs to cancel out weapon reload.
Add feature to allow fire rate sliders.

**Comment by RubyNova** [comment]
I'm not disabling the reload animation. This is simply because its more work that adds nothing for your animation testing. As stated previously, this functionality purely exists for ease of animation testing.

I'll need to know which branch I can get a reproduction for the empty reload issue. I can test the controller but just like last time I can only test the controller side of things. If things are broken in your state machine I can't do much.

Crouching while reloading should work as they're unrelated states, most likely a problem in your state machine, but again I need to get access to the work. Please specify the branch. :)

**Comment by RubyNova** [comment]
Cannot Reproduce: 
```Empty reload causes all the animations to stop working until the ammo is 0 or below again reloading the issue will still persist.```

Incoming fix for:
I made a goof and accidentally inverted reload and tac reload. Oops.

**Comment by Karinexmachina** [comment]
Added basic shooting animation as well as tactical reload and empty reload fix for when empty reload disables all other animations was implemented in the branch feature/character-controller-animation-hooks-api
